REDIS_HOST: ""
REDIS_PASSWORD: ""
CONTAINER_REGISTRY_NAME: ""
CONTAINER_REGISTRY_URL: ""
TAG: ""
APP_ROOT: "."
CLUSTER: ""
MAX_NODES: "12"
MIN_NODES: "2"
MAX_PODS: "22"
MIN_PODS: "2"
WAIT_TIME: "120"
LARGE_QUEUE: "1000"
DECREASE_BY: "4"
DEPLOYMENT: ""
QUEUES: ""
ACR_NAME: ""
RESOURCE_GROUP: ""
SUBSCRIPTION: ""
DOCKER_FILE: "kubernetes_dockerfile"
DAEMONIZE: "false"
SNAPPER_YAML: ""
GUPPY_YAML: ""
